### ISSUE TITLE
Agents updating to incompatible versions

### ISSUE THREAD

**Issue by stevenswager** [deep-security/chef#17]
Appreciate the chef cookbook, makes installing and upgrading agents very easy.  However since the version 11 agent release we have been having issues with agents upgrading to version 11 and the kernel is not compatible. We have opened many tickets with support to get nowhere.  They simply add kernel support for the version we complain about instead of fixing the root cause of not being able to detect which version is compatible or not.  There own deployment script is supposed to detect which version is correct and download the appropriate version, however even that is failing and downloading incompatible agents.  So the cookbook and deployment script both seem a bit useless at the moment if we have to manually choose which agents to update instead of them being able to automatically detect.

**Comment by harrisonchen201703** [comment]
Hi, @stevenswager 
Sorry for the delay.
Thanks for raising the issue to us, we're sorry for what you have encountered.
Before we take any action, may we have following information from your side:
1. On which platform have you encountered this issue?
2. On which kernel version have you encountered this issue?
3. Do you use any cloud or virtualization image provide to create your vm? (e.g. Azure, Amazon or VMWare)
4. Do you use the Deep Security as a Service or you deploy the Deep Security Manager locally?

Thanks.

**Comment by stevenswager** [comment]
1. Ubuntu 16.04
2. Multiple versions, most recent being 4.4.0-1062-aws.  The kernel doesnt show up in the supported matrix for agent version 11, however they still download and try to upgrade to version 11.
3.  AWS
4.  Deep Security as a Service

This doesnt appear to be an issue on the cookbook side, its more of an issue of agents not being able to properly check to see if they can upgrade or not (Trend Micro issue).  The issue though just makes your cookbook not very useful at the moment.  As of this morning the issue is still happening.  So version 11 has been out for 2 months roughly now and still no fix from Trend Micro.

**Comment by DeepSecurityOpenSourceSupport** [comment]
Hi @stevenswager,

Actually this is not related to upgrade, nor a new limitation for 11.0.
The main issue is, when there is a new kernel released, we may have a short gap before we release the new kernel support.
Our PM has already send a message to you to discuss the use case to adopt the latest kernel, so that we can try to enhance the process to reduce the same situation afterward.
If you missed the message, please send a email to deepsecurityopensource@trendmicro.com.

We'll close this case now as the issue is not related to Chef script.

Best Regards,
Deep Security Open Source Support team
